version: '3.8'

services:

  broker:
    image: rabbitmq:3.13.7-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - rabbit
    ports:
      - 8080:15672
      - 5672:5672
      - 5671:5671

  producer:
    build: .
    container_name: producer
    depends_on:
      - broker
    environment:
      BROKER_URL: broker
      EXCHANGE: hello
      QUEUE: world
      ROUTING_KEY: hey
    volumes:
      - .:/app
    working_dir: /app
    command: python producer.py
    networks:
      - rabbit

  consumer:
    build: .
    container_name: consumer
    depends_on:
      - broker
      - producer
    environment:
      BROKER_URL: broker
      EXCHANGE: hello
      QUEUE: world
      ROUTING_KEY: hey
    volumes:
      - .:/app
    working_dir: /app
    command: python consumer.py
    networks:
      - rabbit

networks:
  rabbit:
